name: Scrape free options volatility data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '33 22 * * Sun'

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Scrape
      run: |-
        bash get_options_data.sh        
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
    - name: Generate history
      run: |
        git-history file history.db iv.csv --csv
    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: history
        path: history.db 
